name: ktlintWithFormat

on:
  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/ktlint.yml"
      
jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ktlint
        uses: jeremymouton/ktlint-action@v2
        with:
          format: true
